### ISSUE TITLE
下载链接重定向的问题

### ISSUE THREAD

**Issue by REBOOTERS** [AnyLifeZLB/DownloadInstaller#11]
DownApkRunnable 中使用 HttpURLConnection 进行网络请求，没有处理下载链接存在重定向的情况（很多时候会根据下载地址重定向到一个 CDN 的地址）。这个时候返回的 response  并不是一个实际的 apk 流，而是一次重定向的内容，建议对 resonse code  做一次判断，类似下面这种

```   val connectionUrl = URL(url)
            val conn = connectionUrl.openConnection() as HttpURLConnection
            conn.connect()

            if (conn.responseCode == 302) {
                val redirectUrl = conn.getHeaderField("Location")
           。。。。。
          }
```

或者使用 OkHttp  进行网络请求的处理，其内部会自动完成上述过程。

**Comment by FaceAISDK** [comment]
好的，有没有这种重定向地址，我处理一下 @REBOOTERS

**Comment by REBOOTERS** [comment]
> 好的，有没有这种重定向地址，我处理一下 @REBOOTERS

`https://api.developer.xiaomi.com/autoupdate/updateself/download/fc6b8eba5351dedf2a79dab71c9bb299edcd1fb85AppStore_06af5546730ca4df0191ab263a2ae82b/com.engineer.map_1038.apk`

**Comment by FaceAISDK** [comment]
1.1.4 版本已经解决此问题
