### ISSUE TITLE
downloadApkUrlMd5 = getUpperMD5Str16(downloadApkUrl)

### ISSUE THREAD

**Issue by AnyLife-ZLB** [AnyLifeZLB/DownloadInstaller#2]
这样子不同的App 下载同一个链接的升级包不是会有冲突？
downloadApkUrlMd5 = getUpperMD5Str16(downloadApkUrl+AppUtils.getAppName(mContext))

这样子OK ？

**Comment by FaceAISDK** [comment]
1.0.6 已经处理了这问题
