### ISSUE TITLE
位置应用安装授权

### ISSUE THREAD

**Issue by HouChengYue** [AnyLifeZLB/DownloadInstaller#4]
和一楼有点像，是如果我没有勾选就无法返回，友好的处理是可以返回，只是返回后Toast 提示，然后呢！用户再次点击的时候跳转哪里去授权才好

**Comment by FaceAISDK** [comment]
如果我没有勾选就无法返回，友好的处理是可以返回，我流氓的做成了强制授权作为Feature
后期改为可配置是否要求强制授权安装未知来源（企业级应用需要）

**Comment by FaceAISDK** [comment]
已经可配置      V1.0.9
