### ISSUE TITLE
com.zenglb.downloadinstaller.fileprovider (in package com.xxxx.xxx) is already used by

### ISSUE THREAD

**Issue by enjoy-life-5** [AnyLifeZLB/DownloadInstaller#6]
Installation failed with message Failed to finalize session : INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/com.zxxxxx.xxx==: Can't install because provider name com.zenglb.downloadinstaller.fileprovider (in package com.zjxxxx.xx) is already used by com.xxxx.xxx.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.

楼主，项目换了个包名，然后重新打包安装的时候，会出现这个问题，怎么解决？

**Comment by FaceAISDK** [comment]
@enjoy-life-5 项目换了包名名要把applicationId 也一起换了（或者你卸载老包也可以老）；一台手机的两个App 不可以有个相同的fileprovider存在

-----------------------------------------
        <provider
            android:name=".DownloadInstallerProvider"
            android:authorities="${applicationId}.fileProvider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
